### ISSUE TITLE
wc-admin-api fatal error with order refunds

### ISSUE THREAD

**Issue by justinshreve** [woocommerce/wc-admin#477]
I have an order with the following refund:

<img width="1194" alt="screen shot 2018-09-25 at 8 40 40 am" src="https://user-images.githubusercontent.com/689165/46014864-b6db6f00-c09e-11e8-99f1-47dc067929bb.png">

When `order_product_lookup_store_init` runs, the following fatal occurs:

```
Order ID: 2387

[25-Sep-2018 12:37:49 UTC] PHP Fatal error:  Uncaught Error: Call to undefined method WC_Order_Refund::get_customer_id() in /Users/justin/dev/wc-admin/includes/class-wc-admin-api-init.php:200
Stack trace:
#0 /Users/justin/dev/www/wp-includes/class-wp-hook.php(286): WC_Admin_Api_Init::order_product_lookup_store_init('')
#1 /Users/justin/dev/www/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#2 /Users/justin/dev/www/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#3 /Users/justin/dev/woocommerce/includes/class-wc-post-types.php(470): do_action('woocommerce_aft...')
#4 /Users/justin/dev/www/wp-includes/class-wp-hook.php(286): WC_Post_Types::register_post_types('')
#5 /Users/justin/dev/www/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#6 /Users/justin/dev/www/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#7 /Users/justin/dev/www/wp-settings.php(450): do_action('init')
#8 /Users/justin/dev/www/wp-config.php(91): require_once('/Users/justin/d...')
#9 /Users/justin/dev/www/wp-load.php(37): requ in /Users/justin/dev/wc-admin/includes/class-wc-admin-api-init.php on line 200
```

**Comment by ryelle** [comment]
This is the same error I was getting in p1537304048000100-slack-woo-dash – I think it might have been something with how smooth generator populated orders. No one else could reproduce, so I wiped my site & repopulated it with new orders (I still used smooth generator, and haven't had trouble yet)

**Comment by timmyc** [comment]
Related ( i think ) to p7bje6-1dV-p2

**Comment by joshuatf** [comment]
Resolved by https://github.com/woocommerce/wc-admin/pull/1151.
